---
- name: Deploy echo-server containers
  hosts: all
  become: yes
  tasks:
    - name: Log in to Docker Hub
      docker_login:
        username: andreyylyy
        password: "{{ docker_hub_password }}"
        registry: https://index.docker.io/v1/

    - name: Run echo-server container instance 1
      docker_container:
        name: echo-server-1
        image: andreyylyy/echo-server:latest
        state: started
        restart_policy: always
        ports:
          - "8001:8000"
        env:
          AUTHOR: "Andre"

    - name: Run echo-server container instance 2
      docker_container:
        name: echo-server-2
        image: andreyylyy/echo-server:latest
        state: started
        restart_policy: always
        ports:
          - "8002:8000"
        env:
          AUTHOR: "Andre"

    - name: Run echo-server container instance 3
      docker_container:
        name: echo-server-3
        image: andreyylyy/echo-server:latest
        state: started
        restart_policy: always
        ports:
          - "8003:8000"
        env:
          AUTHOR: "Andre"